name: Deploy Laravel App

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader
          npm install
          npm run prod  # Or npm run build, depending on your setup

      - name: Sync Files to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          REMOTE_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $REMOTE_HOST >> ~/.ssh/known_hosts
          rsync -avz --delete \
            --exclude=".git" \
            --exclude="node_modules" \
            --exclude=".github" \
            --exclude="storage" \
            ./ $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH

      - name: Run Laravel Commands on Server
        env:
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          REMOTE_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          ssh $REMOTE_USER@$REMOTE_HOST << 'EOF'
          cd $REMOTE_PATH
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          EOF
