name: Deploy Laravel Portfolio

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.9.0"

      # Set up PHP with the correct version (e.g., 8.1)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, bcmath, intl, pdo, mysql

      # Install Composer dependencies
      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Generate Application Key
      - name: Generate Application Key
        run: php artisan key:generate

      # Optional: Run tests (if you have tests in your portfolio project)
      # - name: Run Tests
      #   run: php artisan test

      # Build front-end assets if needed (for example, if you use Laravel Mix)
      - name: Build Assets
        run: npm install && npm run prod

      # Move the contents of the public folder to the root
      - name: Move Public Folder to Root
        run: cp -r public/* .

      - name: Move Dist Folder to Root
        run: cp -r ./dist/* .

      - name: Archive generated files to improve upload performance
        run: zip -r deploy.zip .

      - name: Upload generated files as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: deploy.zip

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
